name: WebDriverIO Test Run

on:
  schedule:
    - cron: '30 23 * * *'  # 5:00 AM IST = 11:30 PM UTC daily
  workflow_dispatch:        # ✅ Manual trigger
    inputs:
      suite:
        description: 'Choose the test suite to run'
        required: true
        default: smoke
        type: choice
        options:
          - regression
          - smoke
          - end2end
          - functional
  pull_request:             # ✅ On PR to `main`
    branches:
      - master
  push:                     # ✅ On push to `main`
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run WDIO Tests
        run: npx wdio run ./wdio.conf.js --suite ${{ github.event.inputs.suite || 'smoke' }}
